### ISSUE TITLE
[Bug]: Symfony stream error: "Registering the "symfony" stream wrapper failed"

### ISSUE THREAD

**Issue by radonthetyrant** [ToshY/BunnyNet-PHP#124]
### Package version(s) affected

4.0.1

### Description

When I'm trying to fetch a video state, i'm receiving an error from the library that a stream wrapper cannot be created, which seems to me that the library is somehow either using a wrong implementation of symfony stream resources or i am using an insufficient configuration.

I found this bug: https://github.com/ToshY/BunnyNet-PHP/issues/121 but that uses not the StreamAPI but the BaseAPI.

The current code implementation in our codebase is not from myself so I am digging into this error and requesting help to get to the bottom of this.

My Symfony version is 6.4.4

### How to reproduce

configure the services as follows:

```yaml
  bunny.custom.http_client:
    class: Symfony\Component\HttpClient\Psr18Client

  ToshY\BunnyNet\Client\BunnyClient:
    arguments:
      $client: '@bunny.custom.http_client'

  ToshY\BunnyNet\StreamAPI:
    arguments:
      $apiKey: '%env(BUNNY_STREAM_API_KEY)%'

```

DI the StreamAPI into a service, then call 
```
$this->streamAPI->getVideo($this->libraryId, $videoId);
```

Notice that there is an error with the following stack trace:

```json
{
        "class": "RuntimeException",
        "message": "Registering the \"symfony\" stream wrapper failed.",
        "code": 0,
        "file": "/home/app/application/vendor/symfony/http-client/Response/StreamWrapper.php:65",
        "trace": [
          "/home/app/application/vendor/symfony/http-client/Response/CommonResponseTrait.php:115",
          "/home/app/application/vendor/symfony/http-client/Internal/HttplugWaitLoop.php:140",
          "/home/app/application/vendor/symfony/http-client/Psr18Client.php:107",
          "/home/app/application/vendor/toshy/bunnynet-php/src/Client/BunnyClient.php:106",
          "/home/app/application/vendor/toshy/bunnynet-php/src/StreamAPI.php:182",
          "/home/app/application/src/Video/Util/Stream.php:82",
          ...
        ]
}
```
